name: 'The image deploy to AKS'
description: ' AKS deployment actions.'
inputs:
  REGISTRY:  # path
    description: 'Project Registery '
    required: true
    default: 'quay.io'
  USER_NAME:  # path
      description: 'Registery Username '
      required: true
      default: 'swoturkey'
  IMAGE_NAME:  # path
      description: 'Registery Image Name '
      required: true
      default: 'swoturkey/ratings-web'
  K8S_URL:  # path  
      description: 'AKS k8s url kubectl config view --minify -o "jsonpath={.clusters[0].cluster.server}" '
      required: true
      default: 'dd'
  K8S_SECRET:
      description: 'asdas '
      required: true
      default: 'dd'
outputs:
  Result: 
    description: "Aks Result"
    value: "Aks Deployment finished."
runs:
  
  using: "composite"
  steps:
      - uses: azure/k8s-set-context@v1
        with:
         method: service-account
         k8s-url: ${{inputs.K8S_URL}}
         k8s-secret: ${{ inputs.K8S_SECRET }}
        id: setcontext

      - name: get nodes
        run: kubectl get nodes
        shell: bash